config/routes.rb
Rails.application.routes.draw do
  # namespace :feeds do
  #   get 'albums/discovers/albums'
  # end
  root to: "discovers/photos#index"

  get "/profile", to: "users#show"
  # get "/discover/photos", to: "photos#discover" 
  # get "/discover/albums", to: "albums#discover" 

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:show]

  resources :photos, :albums, only: [:new, :create, :edit, :update, :destroy]

  namespace :discovers do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end

  namespace :feeds do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end
  
  resource :relationships, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to "Fotobook", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control" type="search" placeholder="Search Photo/Album" aria-label="Search">
      <%# <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> %>
    </form>
    <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to profile_path do %>
              <%= image_tag "#{current_user.avatar.picture_url}", class:"img-fluid rounded-circle" %>
              <%= current_user.short_name %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_photo_album_nav.erb
<ul class="nav nav-pills justify-content-center">
  <li class="nav-item">
    <%= link_to "Photo", {controller: "photos", action: action_param}, class:"nav-link #{'active' if ['discovers/photos', 'feeds/photos'].include?(params[:controller])}" %>
  </li>
  <li class="nav-item">
    <%= link_to "Album", {controller: "albums", action: action_param}, class:"nav-link #{'active' if ['discovers/albums', 'feeds/albums'].include?(params[:controller])}" %>
  </li>
</ul>

app/views/shared/_photo_post.html.erb
<div class="col-md-6 feed-photo">
  <div class="card">
    <div class="row">
      <div class="col photo-images">
        <%= image_tag "#{photo.picture.picture_url}", onclick:"onClick(this)" %>
      </div>
      <div class="col">
        <div class="p-0 d-flex flex-column justify-content-around" style="min-height: 200px">
          <div class="card-body p-2">
            <div class="card-info">
              <div class="card-info__avatar">
                <%= link_to user_path(photo.user) do  %>
                  <%= image_tag "#{photo.user.avatar.picture_url}", class: "img-fluid avatar rounded-circle", alt: "avatar"  %>
                </div>
                <div class="card-info__name">
                  <%= link_to "#{photo.user.short_name}", user_path(photo.user) %>
                </div>
              <% end %>
            </div>
            <% if current_user && current_user != photo.user %>
              <div class="d-flex justify-content-center align-items-center h-100">
                <% if current_user.following?(photo.user) %>
                  <%= link_to 'Folowing', relationships_path(user_id: photo.user_id), method: :delete  %>
                <% else %>
                  <%= link_to 'Follow', relationships_path(user_id: photo.user_id), method: :post %>
                <% end %>
              </div>
            <% elsif current_user && current_user == photo.user %>
            <% else %>
              <div class="d-flex justify-content-center align-items-center h-100">
                <%= link_to 'Follow', relationships_path(user_id: photo.user_id), method: :post %>
              </div>
            <% end %>
            <div class="card-title">
              <h5><%= photo.title %></h5>
            </div>
            <div class="card-text">
              <p><%= photo.description %></p>
            </div>
          </div>
          <div class="card-footer__react__time p-2">
            <div class="like-count">
              <i class="fas fa-heart"></i>
              <p>123</p>
            </div>
            <div class="date-time">
              <p><%= photo.updated_at %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<div class="col-md-6 feed-photo">
  <div class="card">
    <div class="row">
      <div class="col photo-images">
        <%= image_tag "#{photo.picture.picture_url}" %>
      </div>
      <div class="col">
        <div class="p-0 d-flex flex-column justify-content-around" style="min-height: 200px">
          <div class="card-body p-2">
            <div class="card-info">
              <div class="card-info__avatar">
                <%= link_to user_path(photo.user) do  %>
                  <%= image_tag "#{photo.user.avatar.picture_url}", class: "img-fluid avatar rounded-circle", alt: "avatar"  %>
                </div>
                <div class="card-info__name">
                  <%= link_to "#{photo.user.short_name}", user_path(photo.user) %>
                </div>
              <% end %>
            </div>
            <% if current_user && current_user != photo.user %>
              <div class="d-flex justify-content-center align-items-center h-100">
                <% if current_user.following?(photo.user) %>
                  <%= link_to 'Folowing', relationships_path(user_id: photo.user_id), method: :delete  %>
                <% else %>
                  <%= link_to 'Follow', relationships_path(user_id: photo.user_id), method: :post %>
                <% end %>
              </div>
            <% elsif current_user && current_user == photo.user %>
            <% else %>
              <div class="d-flex justify-content-center align-items-center h-100">
                <%= link_to 'Follow', relationships_path(user_id: photo.user_id), method: :post %>
              </div>
            <% end %>
            <div class="card-title">
              <h5><%= photo.title %></h5>
            </div>
            <div class="card-text">
              <p><%= photo.description %></p>
            </div>
          </div>
          <div class="card-footer__react__time p-2">
            <div class="like-count">
              <i class="fas fa-heart"></i>
              <p>123</p>
            </div>
            <div class="date-time">
              <p><%= photo.updated_at %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>