config/routes.rb
Rails.application.routes.draw do
  # namespace :feeds do
  #   get 'albums/discovers/albums'
  # end
  root to: "discovers/photos#index"

  get "/profile", to: "users#show"
  # get "/discover/photos", to: "photos#discover" 
  # get "/discover/albums", to: "albums#discover" 

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:show]

  resources :photos, :albums, only: [:new, :create, :edit, :update, :destroy]

  namespace :discovers do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end

  namespace :feeds do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end
  
  resource :relationships, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, length: { maximum: 140 }
  validates :description, length: { maximum: 300 }
  # validate :photo_size_validation
  
  belongs_to :user
  has_one :picture, as: :pictureable, dependent: :destroy

  accepts_nested_attributes_for :picture

  scope :in_public, -> { where(is_private: false) }
  # mount_uploader :photo_url, PhotoUploader

  # def photo_size_validation
  #   if photo_url.size > 5.megabytes
  #     errors.add(:base, "Image must be less than 5Mb")
  #   end
  # end
end

app/controllers/discovers/photos_controller.rb
class Discovers::PhotosController < ApplicationController
  
  def index
    @photos = Photo.in_public.includes(:user, :picture)
  end
end

app/controllers/feeds/photos_controller.rb
class Feeds::PhotosController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @photos = Photo.includes(:user, :picture).in_public.where(user_id: current_user.followings).or(Photo.includes(:user, :picture).in_public.where(user_id: current_user.id))
    # @photos_curr = current_user.photos.includes(:user, :picture).in_public
    # @photos = @photos_following + @photos_curr
    # @photos
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :authenticate_user!
  before_action :find_photo, only: [:edit, :update, :destroy]

  def new
    @photo = current_user.photos.new
  end

  def create
    @photo = current_user.photos.new(photo_params)
    # @photo.valid?
    # puts @photo.errors.full_messages
    

    if @photo.save
      # @photo.picture.pictureable_id = @photo.id
      # @photo.picture.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    # @photo.valid?
    # puts @photo.errors.full_messages
    if @photo.picture && !@photo.picture.changed?
      if @photo.update(photo_params_without_picture)
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    else
      if @photo.update(photo_params)
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_path
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :description, :is_private, picture_attributes: [:pictureable_id, :pictureable_type, :picture_url])
  end

  def photo_params_without_picture
    params.require(:photo).permit(:title, :description, :is_private)
  end

  def find_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/discovers/photos_helper.rb
module Discovers::PhotosHelper
end

app/helpers/feeds/photos_helper.rb
module Feeds::PhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with model: photo do |form| %>
  <div class="form-row">
    <div class="form-group col-md-6 d-flex flex-column justify-content-between">
      <div>
        <%= form.label :title, "Title" %>
        <%= form.text_field :title, class: 'form-control'%>
      </div>
      <div class="w-50">
        <%= form.label :is_private, "Sharing mode" %>
        <%= form.select :is_private, options_for_select([["Public", false], ["Private", true]], "#{false ? params[:action] == 'new' : photo.is_private}"), class: "form-control"%>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, size: "30x10", class: 'form-control'%>
    </div>
    <div class="col-md-2 mt-3">
      <div class="photo-upload-border d-flex justify-content-center align-items-center">
        <% if params[:action] == 'new' %>
          <i class="fas fa-plus"></i>
        <% else %>
          <%= image_tag "#{photo.picture.picture_url}", size:"180x180" %>
        <% end %>
        <%= form.fields_for :picture_attributes do |f| %>
          <%= f.file_field :picture_url, class: "photo-upload", id: "upload-button" %>
          <%= f.hidden_field :pictureable_id, value: photo.id %>
          <%= f.hidden_field :pictureable_type, value: "Photo" %>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= form.submit "Save", class:"btn btn-success mt-5" %>
    <% if params[:action] == 'edit' %>
      <%= link_to "Delete", photo_path(photo), class:"btn btn-danger mt-5", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <% end %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="new-photo col">
  <div class="row">
    <h5 class="mt-4">Edit Photo</h5>
    <hr class="w-100">
  </div>
  <div class="form-new-photo">
    <%= render partial: 'photos/form', locals: {photo: @photo} %>
  </div>
</div>

<%= javascript_pack_tag 'photos' %>

app/views/photos/new.html.erb
<div class="new-photo col">
  <div class="row">
    <h5 class="mt-4">New Photo</h5>
    <hr class="w-100">
  </div>
  <div class="form-new-photo">
    <%= form_with model: @photo do |form| %>
      <div class="form-row">
        <div class="form-group col-md-6 d-flex flex-column justify-content-between">
          <div>
            <%# <label for="">Title</label> %>
            <%= form.label :title, "Title" %>
            <%= form.text_field :title, class: 'form-control'%>
          </div>
          <div class="w-50">
            <%# <label for="">Sharing mode</label> %>
            <%= form.label :is_private, "Sharing mode" %>
            <%= form.select :is_private, options_for_select([["Public", false], ["Private", true]], false), class: "form-control"%>
          </div>
        </div>
        <div class="form-group col-md-6">
          <%# <label for="">Description</label> %>
          <%= form.label :description, "Description" %>
          <%= form.text_area :description, size: "30x10", class: 'form-control'%>
        </div>
        <div class="col-md-2 mt-3">
          <div class="photo-upload-border d-flex justify-content-center align-items-center">
            <i class="fas fa-plus"></i>
            <%= form.fields_for :picture_attributes do |f| %>
              <%= f.file_field :picture_url, class: "photo-upload", id: "upload-button" %>
              <%= f.hidden_field :pictureable_id, value: @photo.id %>
              <%= f.hidden_field :pictureable_type, value: "Photo" %>
            <% end %>
          </div>
        </div>
      </div>
      <div>
        <%= form.submit "Save", class:"btn btn-success mt-5" %>
        <%# <button >Save</button> %>
      </div>
    <% end %>
  </div>
</div>


<%= javascript_pack_tag 'photos' %>