config/routes.rb
Rails.application.routes.draw do
  # namespace :feeds do
  #   get 'albums/discovers/albums'
  # end
  root to: "discovers/photos#index"

  get "/profile", to: "users#show"
  # get "/discover/photos", to: "photos#discover" 
  # get "/discover/albums", to: "albums#discover" 

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users, only: [:show]

  resources :photos, :albums, only: [:new, :create, :edit, :update, :destroy]

  namespace :discovers do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end

  namespace :feeds do
    resources :photos, only: [:index]
    resources :albums, only: [:index]
  end
  
  resource :relationships, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotobook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="row">
      <div class="col-2 sidebar">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to "Feeds", feeds_photos_path, class: "nav-link #{'active' if ['feeds/albums', 'feeds/photos'].include?(params[:controller])}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Discover", discovers_photos_path, class: "nav-link #{'active' if ['discovers/photos', 'discovers/albums'].include?(params[:controller])}" %>
          </li>
        </ul>
      </div>
      <div class="card col-8 main-content">
        <%= yield %>
      </div>
      <div class="col-2 sidebar">
      </div>
    </div>
  </body>
</html>